language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - ./.travis_setup
env:
  - DJANGO="django>=1.11,<2.0"
  - DJANGO="django>=2.0,<2.1"
matrix:
  fast_finish: true
  exclude:
    - python: "2.7"
      env: DJANGO="django>=2.0,<2.1"
    - python: "pypy"
      env: DJANGO="django>=2.0,<2.1"
    - python: "pypy3"
      env: DJANGO="django>=1.11,<2.0"
script:
  - cd ./testproject; coverage run --source=phonenumber_field manage.py test phonenumber_field testapp
after_success:
  coveralls
